FROM lfedge/eve-alpine:591df01e581889c3027514c8a91feaca1c8ad49f as build
ENV PKGS alpine-baselayout
RUN eve-alpine-deploy.sh

WORKDIR /out
COPY scripts /bin
COPY samples /adam
COPY ./bin/adam-linux-amd64 /bin/adam

FROM scratch
COPY --from=build /out/ /
WORKDIR /adam
ENTRYPOINT ["/bin/adam"]
